-- Biblioteca de exercícios global (user_id NULL = disponível para todos).
-- Espelha src/lib/mock-data.ts + src/lib/workout-plan.ts do app Next.js.

INSERT OR IGNORE INTO exercises (id, user_id, name, muscle_group, equipment, type, video_search_term, is_custom) VALUES
('supino-reto', NULL, 'Supino reto', 'peito', 'barra', 'composto', NULL, 0),
('supino-inclinado', NULL, 'Supino inclinado', 'peito', 'barra', 'composto', NULL, 0),
('supino-declinado', NULL, 'Supino declinado', 'peito', 'barra', 'composto', NULL, 0),
('crucifixo', NULL, 'Crucifixo', 'peito', 'halteres', 'isolado', NULL, 0),
('crossover', NULL, 'Crossover', 'peito', 'cabo', 'isolado', NULL, 0),
('puxada-frontal', NULL, 'Puxada frontal', 'costas', 'cabo', 'composto', NULL, 0),
('remada-baixa', NULL, 'Remada baixa', 'costas', 'cabo', 'composto', NULL, 0),
('remada-curvada', NULL, 'Remada curvada', 'costas', 'barra', 'composto', NULL, 0),
('barra-fixa', NULL, 'Barra fixa', 'costas', 'peso-corporal', 'composto', NULL, 0),
('agachamento', NULL, 'Agachamento', 'pernas', 'barra', 'composto', NULL, 0),
('leg-press', NULL, 'Leg press', 'pernas', 'maquina', 'composto', NULL, 0),
('cadeira-extensora', NULL, 'Cadeira extensora', 'pernas', 'maquina', 'isolado', NULL, 0),
('mesa-flexora', NULL, 'Mesa flexora', 'pernas', 'maquina', 'isolado', 'mesa flexora execução correta', 0),
('stiff', NULL, 'Stiff', 'pernas', 'barra', 'composto', NULL, 0),
('desenvolvimento', NULL, 'Desenvolvimento', 'ombros', 'halteres', 'composto', NULL, 0),
('elevacao-lateral', NULL, 'Elevação lateral', 'ombros', 'halteres', 'isolado', 'lateral raise execução', 0),
('elevacao-frontal', NULL, 'Elevação frontal', 'ombros', 'halteres', 'isolado', NULL, 0),
('crucifixo-inverso', NULL, 'Crucifixo inverso', 'ombros', 'halteres', 'isolado', NULL, 0),
('rosca-direta', NULL, 'Rosca direta', 'biceps', 'barra', 'isolado', 'barbell biceps curl execução', 0),
('rosca-alternada', NULL, 'Rosca alternada', 'biceps', 'halteres', 'isolado', NULL, 0),
('rosca-martelo', NULL, 'Rosca martelo', 'biceps', 'halteres', 'isolado', 'hammer curl execução', 0),
('triceps-pulley', NULL, 'Tríceps pulley', 'triceps', 'cabo', 'isolado', NULL, 0),
('triceps-frances', NULL, 'Tríceps francês', 'triceps', 'halteres', 'isolado', NULL, 0),
('triceps-testa', NULL, 'Tríceps testa', 'triceps', 'barra', 'isolado', NULL, 0),
-- Exercícios adicionais do plano "Full Body — Retorno aos treinos"
('supino-maquina', NULL, 'Supino máquina', 'peito', 'maquina', 'composto', 'chest press machine execução', 0),
('triceps-corda', NULL, 'Tríceps corda', 'triceps', 'cabo', 'isolado', 'cable rope triceps pushdown execução', 0),
('abdominal', NULL, 'Abdominal', 'abdomen', 'peso-corporal', 'isolado', 'abdominal crunch execução', 0),
('agachamento-smith', NULL, 'Agachamento no Smith', 'pernas', 'maquina', 'composto', 'Smith machine squat execução', 0),
('supino-inclinado-maquina', NULL, 'Supino inclinado máquina', 'peito', 'maquina', 'composto', 'incline chest press machine execução', 0),
('desenvolvimento-maquina', NULL, 'Desenvolvimento máquina', 'ombros', 'maquina', 'composto', 'machine shoulder press execução', 0),
('stiff-halteres', NULL, 'Stiff com halteres', 'pernas', 'halteres', 'composto', 'dumbbell Romanian deadlift execução', 0),
('supino-halteres', NULL, 'Supino reto com halteres', 'peito', 'halteres', 'composto', 'dumbbell bench press execução', 0),
('puxada-neutra', NULL, 'Puxada neutra', 'costas', 'cabo', 'composto', 'neutral grip lat pulldown execução', 0),
('panturrilha', NULL, 'Panturrilha', 'pernas', 'outro', 'isolado', 'standing calf raise execução', 0);
